name:       pixel
version:    0.1.0.0
github:     "reisen/pixel"
license:    MIT
author:     "Reisen"
maintainer: "reisen@morphism.org"
copyright:  "2018 Reisen"

extra-source-files:
    - README.md

description: A Booru-like Gallery API.

ghc-options:
    -Wall
    -Werror
    -optP-Wno-nonportable-include-path
    -fwarn-tabs
    -fwarn-unused-imports
    -fwarn-missing-signatures
    -fwarn-name-shadowing
    -fwarn-incomplete-patterns

dependencies:
    - base
    - bytestring
    - aeson
    - cryptonite
    - containers
    - data-default-class
    - generic-lens
    - lens
    - mtl
    - protolude
    - servant
    - servant-server
    - servant-multipart
    - sqlite-simple
    - text
    - time
    - uuid
    - wai
    - wai-cors
    - wai-extra
    - warp

default-extensions:
    - BangPatterns
    - ConstraintKinds
    - DataKinds
    - DeriveGeneric
    - DeriveDataTypeable
    - DerivingStrategies
    - DuplicateRecordFields
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedStrings
    - PatternSynonyms
    - PatternGuards
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TemplateHaskell
    - TupleSections
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - TypeApplications
    - ViewPatterns

executables:
    pixel:
        main:        Main.hs
        source-dirs: src/app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N

        dependencies:
            - aeson-typescript
            - eventless
            - optparse-applicative
            - pixel

library:
    source-dirs: src/lib
    dependencies:
        - aeson
        - eventless
        - uuid
